using SpecAnchor.Artefacts;

namespace SpecAnchor.Gates;

/// <summary>
/// The narrow scaffold: from one rule card, generate the acceptance test (red on
/// purpose) and an empty implementation skeleton. Deterministic — free-form code
/// generation stays with the surface (Spec Kit / agent); this exists so the
/// red-before-green discipline starts from the rule, not from the developer's memory.
/// </summary>
public static class Scaffolder
{
    /// <summary>Generates the two source files for a rule card.</summary>
    /// <param name="ruleCardText">The rule card, YAML or JSON.</param>
    /// <returns>File name and content pairs: the acceptance test and the skeleton.</returns>
    /// <exception cref="InvalidOperationException">The card does not parse or lacks required fields.</exception>
    public static IReadOnlyList<(string FileName, string Content)> Scaffold(string ruleCardText)
    {
        if (!ArtefactDocument.TryParse(ruleCardText, out var node, out var error) || node is null)
        {
            throw new InvalidOperationException($"rule card does not parse: {error}");
        }

        var ruleId = node["rule_id"]?.GetValue<string>()
            ?? throw new InvalidOperationException("rule card has no rule_id");
        var statement = (node["statement"]?.GetValue<string>() ?? string.Empty).Trim();
        var context = node["context"]?.GetValue<string>() ?? "Unknown";
        var openQuestions = node["open_questions"]?.AsArray()?.Count ?? 0;

        var safeId = ruleId.Replace('-', '_');
        var ns = $"Discovery.{context}";

        var acceptance = $$"""
            // Generated by `specanchor scaffold {{ruleId}}`. Red on purpose:
            // Definition of Done requires this test to have been red before it is green.
            using Xunit;

            namespace {{ns}}.Acceptance;

            public sealed class {{safeId}}_Acceptance
            {
                [Fact(DisplayName = "{{ruleId}}: {{Truncate(statement, 100)}}")]
                public void Behaviour_matches_the_approved_rule()
                {
                    // {{ruleId}} — {{Truncate(statement, 200)}}
                    // Open questions on the card: {{openQuestions}} (must be 0 before this story enters a sprint).
                    Assert.Fail("Red by design: implement the behaviour, then make this assert the rule.");
                }
            }
            """;

        var skeleton = $$"""
            // Generated by `specanchor scaffold {{ruleId}}`. Implementation skeleton only;
            // the behaviour comes from the approved specification, not from this file.
            namespace {{ns}};

            public sealed class {{safeId}}_Behaviour
            {
                public void Apply()
                {
                    throw new NotImplementedException("{{ruleId}}");
                }
            }
            """;

        return
        [
            ($"{ruleId}.Acceptance.cs", acceptance),
            ($"{ruleId}.Skeleton.cs", skeleton),
        ];
    }

    private static string Truncate(string value, int max) =>
        value.Length <= max ? value : value[..max] + "…";
}
